#!/bin/bash

# Comprehensive guide to run Solidity semantic tests and verify correctness

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   Solidity Correctness Verification Guide                 ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "This guide shows you how to run semantic tests and fuzzers"
echo "to verify the correctness of the Solidity compiler."
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export ETH_EVMONE="${ETH_EVMONE:-$SCRIPT_DIR/deps/lib/libevmone.dylib}"

echo "═══════════════════════════════════════════════════════════"
echo "1. SEMANTIC TESTS (via isoltest)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Semantic tests verify that contracts execute correctly."
echo "There are 1616 semantic tests in total."
echo ""
echo "Commands:"
echo ""
echo "  # Run ALL semantic tests (takes ~5-10 minutes)"
echo "  ./build/test/tools/isoltest"
echo ""
echo "  # Run specific test"
echo "  ./build/test/tools/isoltest -t semanticTests/array/array_push_return_reference"
echo ""
echo "  # Run tests matching pattern"
echo "  ./build/test/tools/isoltest -t 'semanticTests/array/*'"
echo ""
echo "  # Interactive mode (update expectations)"
echo "  ./build/test/tools/isoltest --accept-updates"
echo ""
echo "  # With gas enforcement (verify gas consumption)"
echo "  ./build/test/tools/isoltest --enforce-gas-cost"
echo ""
echo "Try it now? (first 50 tests, ~30 seconds)"
read -p "Run first 50 semantic tests? (y/n): " -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Running first 50 semantic tests..."
    "$SCRIPT_DIR/build/test/tools/isoltest" -t 'semanticTests/abi*' --no-color | head -60
    echo ""
fi

echo "═══════════════════════════════════════════════════════════"
echo "2. ALL TESTS (via soltest)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "soltest runs ALL test suites including:"
echo "  - Semantic tests (runtime execution)"
echo "  - Syntax tests (parsing and type checking)"
echo "  - SMT checker tests (formal verification)"
echo "  - Assembly tests"
echo "  - Yul tests"
echo "  - ABI tests"
echo ""
echo "Commands:"
echo ""
echo "  # Run ALL tests (takes 30-60 minutes!)"
echo "  ./build/test/soltest"
echo ""
echo "  # Run only semantic tests"
echo "  ./build/test/soltest -t SemanticTest"
echo ""
echo "  # Run only syntax tests"
echo "  ./build/test/soltest -t SyntaxTest"
echo ""
echo "  # Run only SMT checker tests"
echo "  ./build/test/soltest -t SMTCheckerTest"
echo ""
echo "  # List all available test suites"
echo "  ./build/test/soltest --list_content=HRF"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "3. FUZZING (OSS-Fuzz Integration)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Fuzzing continuously generates random inputs to find bugs."
echo "Solidity uses Google's OSS-Fuzz infrastructure."
echo ""
echo "The repository includes fuzzer harnesses in:"
echo "  test/tools/ossfuzz/"
echo ""
echo "Available fuzzers:"
echo "  - solc_ossfuzz          (string-based Solidity fuzzer)"
echo "  - solc_ossfuzz_proto    (protobuf-based Solidity fuzzer)"
echo "  - abiv2_ossfuzz_proto   (ABI encoder v2 fuzzer)"
echo "  - const_opt_ossfuzz     (constant optimizer fuzzer)"
echo "  - strictasm_ossfuzz     (strict assembly fuzzer)"
echo "  - yul_ossfuzz_proto     (Yul language fuzzer)"
echo ""
echo "To build and run fuzzers locally:"
echo ""
echo "OPTION A: Quick local fuzzing (without OSS-Fuzz setup)"
echo "  # This requires libfuzzer support in clang"
echo "  mkdir fuzzer-build && cd fuzzer-build"
echo "  cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/libfuzzer.cmake .."
echo "  make ossfuzz -j"
echo "  ./test/tools/ossfuzz/solc_ossfuzz <corpus_dir>"
echo ""
echo "OPTION B: Full OSS-Fuzz environment (recommended)"
echo "  # See: test/tools/ossfuzz/README.md"
echo "  # This uses Docker to match Google's fuzzing infrastructure"
echo "  cd .circleci/docker"
echo "  docker build -t solidity-ossfuzz-local -f Dockerfile.ubuntu.clang.ossfuzz ."
echo "  docker run -v \$(pwd):/src/solidity -ti solidity-ossfuzz-local /bin/bash"
echo ""
echo "Online fuzzing:"
echo "  - Continuous fuzzing: https://oss-fuzz.com/projects/solidity"
echo "  - Bug reports: https://bugs.chromium.org/p/oss-fuzz/issues/list"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "4. QUICK CORRECTNESS CHECK (Recommended First Step)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "For a quick smoke test of correctness, run:"
echo ""
echo "  # 1. Basic semantic tests (5-10 minutes)"
echo "  ./build/test/tools/isoltest"
echo ""
echo "  # 2. Compiler tests (10-15 minutes)"
echo "  ./build/test/soltest -t 'SyntaxTest'"
echo ""
echo "  # 3. End-to-end tests (5 minutes)"
echo "  ./test/cmdlineTests.sh"
echo ""
echo "Total time: ~20-30 minutes for comprehensive correctness check"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "5. ADDITIONAL VERIFICATION TOOLS"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Command-line tests:"
echo "  ./test/cmdlineTests.sh              # Full cmdline test suite"
echo "  ./test/cmdlineTests.sh <testname>   # Specific cmdline test"
echo ""
echo "Interactive tests:"
echo "  ./test/soltest/interactiveTests.sh  # Tests requiring user input"
echo ""
echo "External tests (real-world contracts):"
echo "  # See: scripts/externalTests/"
echo "  # Tests against major DeFi projects (Uniswap, Gnosis, etc.)"
echo ""
echo "Gas tests:"
echo "  ./build/test/soltest -t 'GasCostTest'"
echo "  ./build/test/soltest -t 'GasMeterTest'"
echo ""
echo "SMT Checker (formal verification):"
echo "  # Requires Z3 solver installed"
echo "  ./build/test/soltest -t 'SMTChecker'"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "6. CURRENT BUILD STATUS"
echo "═══════════════════════════════════════════════════════════"
echo ""

if [[ -f "$SCRIPT_DIR/build/solc/solc" ]]; then
    VERSION=$("$SCRIPT_DIR/build/solc/solc" --version | head -1)
    echo "✓ Compiler built: $VERSION"
else
    echo "✗ Compiler not found. Run: cd build && cmake .. && make"
fi

if [[ -f "$SCRIPT_DIR/build/test/tools/isoltest" ]]; then
    echo "✓ isoltest available"
else
    echo "✗ isoltest not built"
fi

if [[ -f "$SCRIPT_DIR/build/test/soltest" ]]; then
    echo "✓ soltest available"
else
    echo "✗ soltest not built"
fi

if [[ -f "$ETH_EVMONE" ]]; then
    echo "✓ evmone available: $ETH_EVMONE"
else
    echo "⚠  evmone not found (needed for semantic tests)"
    echo "   Install: cd deps && git clone https://github.com/ethereum/evmone.git"
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "QUICK START EXAMPLES"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "# Example 1: Run all semantic tests"
echo "./build/test/tools/isoltest"
echo ""
echo "# Example 2: Run tests for arrays"
echo "./build/test/tools/isoltest -t 'semanticTests/array/*'"
echo ""
echo "# Example 3: Run all syntax tests"
echo "./build/test/soltest -t SyntaxTest"
echo ""
echo "# Example 4: Check compiler version"
echo "./build/solc/solc --version"
echo ""
echo "# Example 5: Run smoke tests (fast)"
echo "./build/test/tools/isoltest -t 'semanticTests/smoke/*'"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "DOCUMENTATION"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Test documentation:"
echo "  - test/README.md                     # Overview of test infrastructure"
echo "  - test/tools/ossfuzz/README.md       # Fuzzing guide"
echo "  - docs/contributing.rst              # Contributing and testing guide"
echo ""
echo "Online resources:"
echo "  - https://docs.soliditylang.org/en/latest/contributing.html"
echo "  - https://github.com/ethereum/solidity/blob/develop/test/README.md"
echo ""
